---
output: 
html_document:
  number_sections=TRUE
pagetitle: Assignment_9
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Assignment 9**

In this assignment, you will use R (within R-Studio) to:
  
+ Load and clean a real data set
+ Conduct exploratory analyses, including informative figures
+ Build and test appropriate models
+ Draw conclusions about your data
+ Combine all of the above into a well-documented R-Markdown report and export (knit) it into an HTML file

**All file paths should be relative, starting from *your* Assignment_9 directory!!**

**This means that you need to create a new R-Project named "Assignment_9.Rproj" in your Assignment_9 directory, and work from scripts within that.**


## **For credit...**

1.  Push a completed version of your Rproj and R-markdown file (details at end of this assignment) to GitHub
2.  Your score will also depend on your analyses and presentation of your final report

____________

# Your tasks:

+ Use the data set "/Data/GradSchool_Admissions.csv"
+ You will explore and model the predictors of graduate school admission
  - the "admit" column is coded as 1=success and 0=failure (that's binary, so model appropriately)
  - the other columns are the GRE score, the GPA, and the rank of the undergraduate institution, where I is "top-tier."
+ Document your data explorations, figures, and conclusions in a reproducible R-markdown report
+ That means I want to see, in your html report, your process of model evaluation and selection. Here's an [example](https://gzahn.github.io/data-course/Repository/Assignments/Assignment_9/example.html){target="_blank"}
+ Upload your **self-contained** R project, including knitted HTML report, to GitHub in *your* Assignment_9 directory

data <- read.csv("Data/GradSchool_Admissions.csv")
head(data)

str(data)
summary(data)

data$rank <- as.factor(data$rank)

table(data$admit)

boxplot(gre ~ admit, data = data,
        main = "GRE vs Admission",
        xlab = "Admission (0 = No, 1 = Yes)",
        ylab = "GRE Score")

boxplot(gpa ~ admit, data = data,
        main = "GPA vs Admission",
        xlab = "Admission",
        ylab = "GPA")

table(data$rank, data$admit)

model1 <- glm(admit ~ gre + gpa + rank,
              data = data,
              family = binomial)

summary(model1)


model2 <- glm(admit ~ gpa + rank,
              data = data,
              family = binomial)

model3 <- glm(admit ~ rank,
              data = data,
              family = binomial)

AIC(model1, model2, model3)

data$predicted <- predict(model1, type = "response")
head(data)

exp(coef(model1))

anova(model3, model2, model1, test = "Chisq")